export {NextLaunchCont} from './NextLaunch/index.tsx'
export{LaunchesCont} from './Launchhes/index.tsx'
export{LaunchesDetails} from './LaunchDetails/index.tsx'
export{EventsCont} from './Events/index.tsx'
export {CompanyInfoCont} from './About/index.tsx'